### PR TITLE
Use generated operations

### PR DESCRIPTION
**Pull request by ghost**
Depends on Trax-air/swagger-parser#21

Uses generated operations and operations with an operationId, otherwise there's no change.

### CODE REVIEW

**Comment by ghost** [comment]
@beanqueen

**Comment by cyprieng** [comment]
Can you fix the test, so I could merge ? Thanks

**Comment by cyprieng** [comment]
Ok sorry, it seems there is the same issue on master #32

**Comment by ghost** [comment]
There's an issue with connexion here; I want to send them a PR. Basically, connexion errors out when it doesn't get an operationId, instead of reporting a 500 or 404 or whatever makes most sense to them for that path.

I'll link the PR here when I've made it.

**Comment by ghost** [comment]
It turns out it's better to make two PRs. The first is zalando/connexion#274 - it just makes errors from bad operationIds more readable.

The next PR will be handling those errors at run-time, turning them into some 5xx code.

**Comment by ghost** [comment]
So I ended up making a bunch of PRs, but the one that matters would be zalando/connexion#278

Others:
- zalando/connexion#274
- zalando/connexion#275
- zalando/connexion#276
- zalando/connexion#277 (already merged)

**Comment by ghost** [comment]
So, it seems that connexion merged all my PRs, after some cleanup and discussion. Yay!

That should be enough to fix the tests, at least with the master of connexion

**Comment by cyprieng** [comment]
Good!
But we need them to update connexion on pypi, so we could update our requirements.

**Comment by cyprieng** [comment]
@jfinkhaeuser connexion has been updated on pypi. Can you update the requirements.txt ?

**Comment by ghost** [comment]
Thanks to #36, this is now basically a useless PR. Still, look at the diff (flake8 fix, largely).

**Pull request merged**
