### PR TITLE
add support for custom headers

### LINKED ISSUE #14: Add Support for Custom Headers
Some applications may require custom headers for their requests.

I'm not sure how this should be implemented. My first inclination is to have an kwarg for swagger_tester that should be a list of tuples. If I don't have any feedback i will try to implement this later today.

### PR DESCRIPTION
**Pull request by zdelagrange**
Closes #14

### CODE REVIEW

**Comment by zdelagrange** [comment]
Master is currently broken for me locally as well.

**Comment by flavianh** [comment]
Master is broken? @cyprien-g can you confirm?

**Comment by flavianh** [comment]
You need to add test cases to check your code for corectness @zdelagrange. Add a "header" parameter in our swagger file and check that it is indeed tested

**Comment by cyprieng** [comment]
Master is working again. But there is an error in your header creation: https://travis-ci.org/Trax-air/swagger-tester/jobs/117155008

**Comment by flavianh** [comment]
Again, if you could add a test case, that would be great

**Comment by zdelagrange** [comment]
I hate to keep passing the buck on these tests, but is this endpoint broken on petstore.swagger.io?

**Comment by cyprieng** [comment]
I restarted the test and it passed. We need to get rid of the online swagger api test.

**Comment by cyprieng** [comment]
It seems good for me. @traxair what do you think ?

**Comment by flavianh** [comment]
The test case doesn't seem to be really a test case. It's good that we have a header parameter, but there should be some other validation

**Comment by cyprieng** [comment]
Yes, but it is because we don't have real tests for now. That's why I opened #19

**Comment by flavianh** [comment]
Ok cool, good for me then

**Comment by cyprieng** [comment]
@zdelagrange Your contribution is really appreciated, and is available in the last release on pypi :smile:

**Comment by zdelagrange** [comment]
thanks @cyprieng I can relate with the "no real tests" thing. thanks for being active on this repo! this is a really cool package!

**Pull request merged**
