### PR TITLE
Fixes #51

### LINKED ISSUE #51: Test fails if the server's url contains the basePath
https://github.com/Trax-air/swagger-tester/blob/fb5063bd3a89202c1e60234101fb466f59cfc97c/swagger_tester/swagger_tester.py#L313 should not remove all occurrences of basePath in app_url, just the occurrences of basePath at the end. If the server's url contains the basePath, then all occurrences will be removed and this will fail e.g. if basePath is `/` or not defined (which defaults to `/`) and the testing url is `http://127.0.0.1:8080`, this will fail with exception:
```
requests.exceptions.InvalidURL: Failed to parse: http:127.0.0.1:8080
```

### PR DESCRIPTION
**Pull request by ThomasHickman**
Fixes #51, by only removing basePath at the end of urls

### CODE REVIEW

**Comment by flavianh** [comment]
@ThomasHickman thanks for your contribution! Could you write a test for this? One that fails with the previous behavior but which your PR allows to pass

**Comment by cyprieng** [comment]
Thanks for your contribution! Could you fix the flake 8 issue `/tests/test_swagger-tester.py:72:1: E302 expected 2 blank lines, found 1` so we can merge ?

**Comment by cyprieng** [comment]
@flavianh any clue on the build error `ERROR: InterpreterNotFound: pypy` ?

**Comment by flavianh** [comment]
@cyprieng Maybe check this: https://github.com/travis-ci/travis-ci/issues/6865 
Setting pypy-5.4.1 in the travis.yml file could fix the issue: https://github.com/Yelp/venv-update/blob/19c18924afb55d23333150bf3bdb66da995b046f/.travis.yml#L12

**Comment by cyprieng** [comment]
@flavianh thanks I have fixed the build on master :+1: 
@ThomasHickman Can you update your branch with master (to check that the test are green) ?

**Pull request merged**
